import express from 'express';
import cors from 'cors';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { SSEServerTransport } from '@modelcontextprotocol/sdk/server/sse.js';
import { logger } from '../logger';
import { BrokerRegistry } from '../brokers/registry';
import { createOAuthHandlers } from './oauth';

// Each SSE connection needs its own McpServer instance — the SDK does not allow
// a single server to connect to more than one transport simultaneously.
type ServerFactory = () => McpServer;

export interface SseAppOptions {
  maxSessions?: number;
  rateLimit?: number;
  apiKey?: string;
  corsOrigin?: string;
  trustProxy?: boolean;
  baseUrl?: string;
  tokenTtlSeconds?: number;
}

export function createSseApp(
  serverFactory: ServerFactory,
  registry: BrokerRegistry,
  options: SseAppOptions = {}
): { app: express.Application; transports: Map<string, SSEServerTransport> } {
  const app = express();
  const maxSessions = options.maxSessions ?? 100;
  const rateLimit = options.rateLimit ?? 10;

  if (options.trustProxy) app.set('trust proxy', 1);

  if (options.corsOrigin) {
    app.use(cors({
      origin: options.corsOrigin === '*' ? '*' : options.corsOrigin.split(',').map(o => o.trim()),
    }));
  }
  app.use(express.json());

  const oauth = createOAuthHandlers({
    baseUrl: options.baseUrl ?? 'http://localhost:3000',
    apiKey: options.apiKey,
    tokenTtlSeconds: options.tokenTtlSeconds,
  });
  // Mount OAuth routes BEFORE rate limiter — requests to OAuth endpoints are matched
  // here and handled immediately, so they never reach the rate limiter below.
  oauth.mountRoutes(app);
  app.use(oauth.createMiddleware());

  const sessionCounts = new Map<string, { count: number; resetAt: number }>();
  setInterval(() => {
    const now = Date.now();
    for (const [sid, entry] of sessionCounts) {
      if (now > entry.resetAt) sessionCounts.delete(sid);
    }
  }, 60_000).unref();

  app.use((req, res, next) => {
    if (req.path === '/health') return next();
    const sid = req.ip ?? 'default';
    const now = Date.now();
    const entry = sessionCounts.get(sid);
    if (!entry || now > entry.resetAt) { sessionCounts.set(sid, { count: 1, resetAt: now + 1000 }); return next(); }
    if (entry.count >= rateLimit) { res.status(429).json({ error: 'Rate limit exceeded. Please wait before sending additional requests.' }); return; }
    entry.count++;
    next();
  });

  app.get('/health', (_req, res) => res.json({ status: 'ok', brokers: registry.count() }));

  // Session map keyed by UUID sessionId (generated by MCP SDK).
  // Note: there is no per-session IP or token binding — any authenticated client
  // that knows a sessionId can POST to /messages for that session. This is acceptable
  // because sessionIds are UUIDs (brute-forcing is infeasible) and this server does
  // not support multi-tenant deployments sharing a single API key.
  const transports = new Map<string, SSEServerTransport>();

  app.get('/sse', async (req, res, next) => {
    try {
      if (transports.size >= maxSessions) {
        res.status(503).json({ error: 'Too many concurrent sessions. Try again later.' }); return;
      }
      const transport = new SSEServerTransport('/messages', res);
      // Register cleanup BEFORE connect so it runs even if connect throws
      req.on('close', () => transports.delete(transport.sessionId));
      transports.set(transport.sessionId, transport);
      try {
        // Create a fresh McpServer per connection — the SDK forbids reusing a single
        // server instance across multiple transports simultaneously.
        const mcpServer = serverFactory();
        await mcpServer.server.connect(transport);
        logger.info(`SSE client connected: ${transport.sessionId}`);
      } catch (err) {
        transports.delete(transport.sessionId);
        throw err;
      }
    } catch (err) {
      next(err);
    }
  });

  app.post('/messages', async (req, res, next) => {
    try {
      const raw = req.query['sessionId'];
      const sessionId = typeof raw === 'string' ? raw : undefined;
      if (!sessionId) { res.status(400).json({ error: 'Missing sessionId' }); return; }
      const transport = transports.get(sessionId);
      if (!transport) { res.status(404).json({ error: 'Session not found' }); return; }
      await transport.handlePostMessage(req, res);
    } catch (err) {
      next(err);
    }
  });

  // Error handler — must be 4-argument to be recognized by Express
  app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    logger.error('Unhandled SSE error', { error: String(err) });
    if (!res.headersSent) res.status(500).json({ error: 'Internal server error' });
  });

  return { app, transports };
}

export async function startSseTransport(serverFactory: ServerFactory, registry: BrokerRegistry): Promise<void> {
  const rawPort = parseInt(process.env['PORT'] ?? '3000', 10);
  const port = isNaN(rawPort) ? 3000 : rawPort;
  const rawRateLimit = parseInt(process.env['MCP_RATE_LIMIT_RPS'] ?? '10', 10);
  const rawMaxSessions = parseInt(process.env['MCP_MAX_SESSIONS'] ?? '100', 10);
  const trustProxy = process.env['TRUST_PROXY'];
  const baseUrl = process.env['BASE_URL'] ?? `http://localhost:${port}`;
  const rawTokenTtl = parseInt(process.env['OAUTH_TOKEN_TTL_SECONDS'] ?? '3600', 10);

  const { app } = createSseApp(serverFactory, registry, {
    maxSessions: isNaN(rawMaxSessions) ? 100 : rawMaxSessions,
    rateLimit: isNaN(rawRateLimit) ? 10 : rawRateLimit,
    apiKey: process.env['MCP_API_KEY'],
    corsOrigin: process.env['CORS_ORIGIN'],
    trustProxy: trustProxy === '1' || trustProxy === 'true',
    baseUrl,
    tokenTtlSeconds: isNaN(rawTokenTtl) ? 3600 : rawTokenTtl,
  });

  app.listen(port, () => logger.info(`MCP SSE server on port ${port}`));
}
