import crypto from 'crypto';
import express from 'express';
import cors from 'cors';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { SSEServerTransport } from '@modelcontextprotocol/sdk/server/sse.js';
import { logger } from '../logger';
import { BrokerRegistry } from '../brokers/registry';

function timingSafeEqual(a: string, b: string): boolean {
  try {
    const maxLen = Math.max(Buffer.byteLength(a), Buffer.byteLength(b));
    const ab = Buffer.alloc(maxLen);
    const bb = Buffer.alloc(maxLen);
    ab.write(a);
    bb.write(b);
    return crypto.timingSafeEqual(ab, bb);
  } catch {
    return false;
  }
}

export interface SseAppOptions {
  maxSessions?: number;
  rateLimit?: number;
  apiKey?: string;
  corsOrigin?: string;
  trustProxy?: boolean;
}

export function createSseApp(
  server: McpServer,
  registry: BrokerRegistry,
  options: SseAppOptions = {}
): { app: express.Application; transports: Map<string, SSEServerTransport> } {
  const app = express();
  const maxSessions = options.maxSessions ?? 100;
  const rateLimit = options.rateLimit ?? 10;
  const apiKey = options.apiKey;

  if (options.trustProxy) app.set('trust proxy', 1);

  if (options.corsOrigin) {
    app.use(cors({
      origin: options.corsOrigin === '*' ? '*' : options.corsOrigin.split(',').map(o => o.trim()),
    }));
  }
  app.use(express.json());

  if (apiKey) {
    app.use((req, res, next) => {
      if (req.path === '/health') return next();
      const auth = req.headers['authorization'] ?? '';
      if (!timingSafeEqual(auth, `Bearer ${apiKey}`)) {
        res.status(401).json({ error: 'Unauthorized' }); return;
      }
      next();
    });
  }

  const sessionCounts = new Map<string, { count: number; resetAt: number }>();
  setInterval(() => {
    const now = Date.now();
    for (const [sid, entry] of sessionCounts) {
      if (now > entry.resetAt) sessionCounts.delete(sid);
    }
  }, 60_000).unref();

  app.use((req, res, next) => {
    if (req.path === '/health') return next();
    const sid = req.ip ?? 'default';
    const now = Date.now();
    const entry = sessionCounts.get(sid);
    if (!entry || now > entry.resetAt) { sessionCounts.set(sid, { count: 1, resetAt: now + 1000 }); return next(); }
    if (entry.count >= rateLimit) { res.status(429).json({ error: 'Rate limit exceeded. Please wait before sending additional requests.' }); return; }
    entry.count++;
    next();
  });

  app.get('/health', (_req, res) => res.json({ status: 'ok', brokers: registry.count() }));

  // Session map keyed by UUID sessionId (generated by MCP SDK).
  // Note: there is no per-session IP or token binding — any authenticated client
  // that knows a sessionId can POST to /messages for that session. This is acceptable
  // because sessionIds are UUIDs (brute-forcing is infeasible) and this server does
  // not support multi-tenant deployments sharing a single API key.
  const transports = new Map<string, SSEServerTransport>();

  app.get('/sse', async (req, res, next) => {
    try {
      if (transports.size >= maxSessions) {
        res.status(503).json({ error: 'Too many concurrent sessions. Try again later.' }); return;
      }
      const transport = new SSEServerTransport('/messages', res);
      // Register cleanup BEFORE connect so it runs even if connect throws
      req.on('close', () => transports.delete(transport.sessionId));
      transports.set(transport.sessionId, transport);
      try {
        await server.server.connect(transport);
        logger.info(`SSE client connected: ${transport.sessionId}`);
      } catch (err) {
        transports.delete(transport.sessionId);
        throw err;
      }
    } catch (err) {
      next(err);
    }
  });

  app.post('/messages', async (req, res, next) => {
    try {
      const raw = req.query['sessionId'];
      const sessionId = typeof raw === 'string' ? raw : undefined;
      if (!sessionId) { res.status(400).json({ error: 'Missing sessionId' }); return; }
      const transport = transports.get(sessionId);
      if (!transport) { res.status(404).json({ error: 'Session not found' }); return; }
      await transport.handlePostMessage(req, res);
    } catch (err) {
      next(err);
    }
  });

  // Error handler — must be 4-argument to be recognized by Express
  app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    logger.error('Unhandled SSE error', { error: String(err) });
    if (!res.headersSent) res.status(500).json({ error: 'Internal server error' });
  });

  return { app, transports };
}

export async function startSseTransport(server: McpServer, registry: BrokerRegistry): Promise<void> {
  const rawPort = parseInt(process.env['PORT'] ?? '3000', 10);
  const port = isNaN(rawPort) ? 3000 : rawPort;
  const rawRateLimit = parseInt(process.env['MCP_RATE_LIMIT_RPS'] ?? '10', 10);
  const rawMaxSessions = parseInt(process.env['MCP_MAX_SESSIONS'] ?? '100', 10);
  const trustProxy = process.env['TRUST_PROXY'];

  const { app } = createSseApp(server, registry, {
    maxSessions: isNaN(rawMaxSessions) ? 100 : rawMaxSessions,
    rateLimit: isNaN(rawRateLimit) ? 10 : rawRateLimit,
    apiKey: process.env['MCP_API_KEY'],
    corsOrigin: process.env['CORS_ORIGIN'],
    trustProxy: trustProxy === '1' || trustProxy === 'true',
  });

  app.listen(port, () => logger.info(`MCP SSE server on port ${port}`));
}
